## Best Practices---->>>>

1. Preprocessing And Cleaning

2. Train Test Split

3. BOW,TFIDF,Word2vec

4. Train ML algorithms

In [1]:
# Load the dataset
import pandas as pd
data=pd.read_csv('all_kindle_review.csv')
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [4]:
data.shape

(12000, 11)

In [14]:
df=data[['reviewText','rating']]
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [3]:
df.shape

(12000, 2)

In [5]:
## Missing Values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [6]:
df['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [7]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

## 1.Preprocessing And Cleaning

In [15]:
## postive review is 1 and negative review is 0


df['rating'] = df['rating'].apply(lambda x:0 if x<3 else 1)

# (1,2)= Negative Review
# (3,4,5)= Positive Review

C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\73454769.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].apply(lambda x:0 if x<3 else 1)


In [16]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [ ]:

df['reviewText'] = df['reviewText'].str.lower()

C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\2510406002.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].str.lower()


In [18]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [20]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

from bs4 import BeautifulSoup

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))

C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\701754434.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))


In [22]:
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))


C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\1357754929.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))


In [23]:
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))


C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\3231385.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))


In [28]:
## Remove html tags

from bs4 import BeautifulSoup
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())


C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\972122860.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())


In [29]:

## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))


C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\1785352144.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))


In [30]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

## Lemmatization

In [31]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [32]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])



df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\4214746389.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))


In [33]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

## 2. Train Test Split

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],
                                              test_size=0.20)

## 3. Applying B.O.W.

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

bow=CountVectorizer()


In [36]:
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

## 4. Applying TF_IDF

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()


In [38]:

X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

## 5. Training ML Algo :-
### Applying Naive Bayes Algo, Because it usually fits with Sparse Matrix DataSet

In [39]:
from sklearn.naive_bayes import GaussianNB

nb_model_bow=GaussianNB().fit(X_train_bow,y_train)

nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report


y_pred_bow = nb_model_bow.predict(X_test_bow)

y_pred_tfidf = nb_model_tfidf.predict(X_test_tfidf)

In [41]:
print("BOW accuracy: ",accuracy_score(y_test, y_pred_bow))

confusion_matrix(y_test, y_pred_bow)

BOW accuracy:  0.5754166666666667


array([[493, 272],
       [747, 888]], dtype=int64)

In [42]:
print("TFIDF accuracy: ",accuracy_score(y_test, y_pred_tfidf))

confusion_matrix(y_test,y_pred_tfidf)

TFIDF accuracy:  0.5758333333333333


array([[475, 290],
       [728, 907]], dtype=int64)

## As the Accuracy of both the models- "BOW" and "TFIDF" is NOT good.
## 6. Hence, Appying -->> AvgWord2Vec

In [43]:
!pip install gensim

In [44]:
import gensim
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import numpy as np


In [52]:

# Tokenize for Word2Vec
df['tokens'] = df['reviewText'].apply(lambda x: x.split())

C:\Users\DELL\AppData\Local\Temp\ipykernel_24052\2625205093.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokens'] = df['reviewText'].apply(lambda x: x.split())


In [53]:
# Train Word2Vec
w2v_model = Word2Vec(sentences=df['tokens'], vector_size=300, window=5, min_count=2, workers=4, sg=1)


In [54]:
# Average vectors
def get_avg_vector(tokens, model, k=100):
    valid_words = [word for word in tokens if word in model.wv]
    return np.mean(model.wv[valid_words], axis=0) if valid_words else np.zeros(k)


In [55]:
X_vectors = np.array([get_avg_vector(tokens, w2v_model, 100) for tokens in df['tokens']])
y = df['rating']


In [56]:
# Split
X_train, X_test, y_train, y_test = train_test_split(X_vectors, y, test_size=0.2, random_state=42)

# Train
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [57]:
# Predict & Evaluate
y_pred = clf.predict(X_test)


print(accuracy_score(y_test,y_pred))

print(classification_report(y_test, y_pred))


0.8104166666666667
              precision    recall  f1-score   support

           0       0.78      0.61      0.68       803
           1       0.82      0.91      0.86      1597

    accuracy                           0.81      2400
   macro avg       0.80      0.76      0.77      2400
weighted avg       0.81      0.81      0.80      2400



In [58]:
confusion_matrix(y_test,y_pred)

array([[ 490,  313],
       [ 142, 1455]], dtype=int64)