# BOW,TFIDF, Machine Learning Algorithms

#### 1. Preprocessing And Cleaning
#### 2. Train Test Split
#### 3. BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}

In [1]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection',
                    sep='\t',names=["label","message"])

In [2]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## 1. Data Cleaning And PreProcessing

In [3]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])

    review=review.lower()
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    
    review=' '.join(review)
    corpus.append(review)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Bag Of Words (BOW)

In [7]:
## Output Features// Dependent Features

y = pd.get_dummies(messages['label'])

y

ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [8]:
y = y.iloc[:,0].values      ## Selecting Ham column

In [9]:
y

array([ True,  True, False, ...,  True,  True,  True])

## 2. Train Test Split

In [10]:


from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

##### Create the Bag OF Words model

In [11]:

from sklearn.feature_extraction.text import CountVectorizer


## for Binary BOW enable binary=True

cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [12]:
len(X_train),len(y_train)

(4457, 4457)

In [13]:
## independent features

X_train=cv.fit_transform(X_train).toarray()

X_test=cv.transform(X_test).toarray()

In [16]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [17]:
cv.vocabulary_

{'congrat': 403,
 'treat': 2190,
 'mail': 1244,
 'day': 483,
 'thru': 2123,
 'respect': 1736,
 'mother': 1365,
 'home': 948,
 'check': 331,
 'also': 57,
 'came': 282,
 'room': 1760,
 'friend': 732,
 'help': 913,
 'us': 2279,
 'problem': 1653,
 'give': 783,
 'stupid': 2012,
 'suggest': 2021,
 'land': 1098,
 'anoth': 66,
 'account': 7,
 'success': 2018,
 'lt': 1224,
 'decim': 500,
 'gt': 857,
 'balanc': 140,
 'rs': 1767,
 'transact': 2187,
 'id': 988,
 'lt decim': 1225,
 'decim gt': 501,
 'rs lt': 1768,
 'lt gt': 1226,
 'messag': 1297,
 'food': 699,
 'sorri': 1938,
 'call': 246,
 'later': 1114,
 'meet': 1286,
 'sorri call': 1939,
 'call later': 259,
 'later meet': 1115,
 'yar': 2468,
 'say': 1793,
 'got': 833,
 'send': 1823,
 'first': 688,
 'ok': 1483,
 'lor': 1203,
 'readi': 1693,
 'yet': 2484,
 'send home': 1828,
 'ok lor': 1486,
 'sign': 1875,
 'matur': 1273,
 'start': 1977,
 'big': 168,
 'thing': 2110,
 'actual': 15,
 'understand': 2233,
 'small': 1908,
 'nice': 1431,
 'even': 621,
 

#### Using NAIVE_BAYES

In [18]:
from sklearn.naive_bayes import MultinomialNB

spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [19]:
y_pred = spam_detect_model.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score,classification_report

In [21]:
accuracy_score(y_test,y_pred)

0.9847533632286996

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.96      0.92      0.94       142
        True       0.99      0.99      0.99       973

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



## 3. BOW And TF-IDF (Sentences--->vectors) 
## {Preventing Data Leakage}

### TF_IDF -->> (Term Frequency-Inverse Document Frequency)

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

### Train Test Split

In [24]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [25]:
## independent features
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [26]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.213, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0.222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0,

In [27]:
tv.vocabulary_

{'test': 2071,
 'yesterday': 2484,
 'someth': 1914,
 'let': 1125,
 'know': 1068,
 'day': 479,
 'get': 761,
 'wk': 2407,
 'pl': 1559,
 'dont': 539,
 'worri': 2426,
 'relax': 1710,
 'also': 53,
 'anyth': 70,
 'ur': 2235,
 'past': 1522,
 'need': 1383,
 'tell': 2060,
 'let know': 1126,
 'pl pl': 1562,
 'pl dont': 1561,
 'tht': 2107,
 'wat': 2332,
 'brother': 215,
 'fli': 686,
 'amaz': 55,
 'letter': 1127,
 'give': 777,
 'mean': 1252,
 'room': 1752,
 'moon': 1329,
 'eye': 632,
 'see': 1802,
 'result': 1735,
 'lie': 1131,
 'mother': 1337,
 'law': 1101,
 'woman': 2415,
 'plu': 1578,
 'two': 2190,
 'one': 1469,
 'avail': 115,
 'rd': 1680,
 'today': 2131,
 'offer': 1445,
 'claim': 344,
 'worth': 2429,
 'discount': 526,
 'voucher': 2302,
 'text': 2072,
 'ye': 2469,
 'savamob': 1779,
 'member': 1263,
 'mobil': 1307,
 'cs': 446,
 'sub': 2011,
 'unsub': 2224,
 'repli': 1720,
 'claim ur': 350,
 'ur worth': 2257,
 'worth discount': 2430,
 'discount voucher': 527,
 'text ye': 2080,
 'ye savamob': 2472

#### Using NAIVE_BAYES

In [28]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [29]:
#prediction

y_pred=spam_tfidf_model.predict(X_test)

In [30]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9820627802690582


In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.87      0.99      0.93       133
        True       1.00      0.98      0.99       982

    accuracy                           0.98      1115
   macro avg       0.94      0.99      0.96      1115
weighted avg       0.98      0.98      0.98      1115

